image: python:3.9

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest

deploy:
  stage: deploy
  script:
    - |
      echo "Deploying application..."
      git config --global user.email 
      git config --global user.name 
      git remote add github 
      git push github main
  only:
    - main
